### ISSUE TITLE
shortcut for Path.isDirectory and Path.isRegularFile

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#111]
*Platform* (JVM, JS and/or Android): jdk8

## Code related feature
```
expect(Paths.get("xyz")).isDirectory()
expect(Paths.get("xyz")).isRegularFile()
//instead of
expect(Paths.get("xyz")).feature(Files::isDirectory) { toBe(true) }
expect(Paths.get("xyz")).feature(Files::isRegularFile) { toBe(true) }
```
Following the things you need to do:

*domain*
- extend PathAssertions with `isDirectory` and `isRegularFile` (as for `exists`)
- modify PathAssertionsBuilder, delegate to pathAssertions (as for `exists`)
- delegate implementation to robstoll-lib in PathAssertionsImpl (as for `exists`)

*lib*
- implement _isDirectory and _isRegularFile in pathAssertions.kt in robstoll-lib (I have already setup a dependency to niok which provides Path.isDirectory and Path.isRegularFile) => see _exists as example, better use a descriptive Assertion instead of creating a feature assertion, less noisy, more readable, I would use `DescriptionBasic.IS` as description

*api*
- add  `isDirectory` and `isRegularFile` (`exists` as guideline)  and `@since 0.9.0` (adopt to current version) to the KDOC
- extend PathAssertionsSpec in specs-common

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](http://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by jGleitz** [comment]
It feels odd to have `isRegularFile` and `isDirectory`, but not `isSymbolicLink`, since those are the most common file types from my point of view. Would you agree to add `isSymbolicLink`, too?

Note: I am planning to have the assertions do more than being mere shortcuts. They should also report what the actual file type was.

**Comment by robstoll** [comment]
I included it myself first but as I never had a test where this was required, I excluded it again. Thus I would suggest you ask yourself the same question, do you have a test where you need it? If not, I wouldn't add it yet and wait until someone requires it. However, I will not reject a PR if you want to include it in any case.

Concerning additional checks, that's perfectly fine with me. But please do not add additional assertions use a descriptive assertion with a failure hint instead.

**Comment by jGleitz** [comment]
I see your point. I do not have a concrete use case in mind, it just seemed reasonable to say “c” when we are saying “a” and “b”

**Comment by jGleitz** [comment]
We have a use case in https://github.com/robstoll/tutteli-spek-extensions/pull/10, though ;)

**Comment by robstoll** [comment]
Let me guess, you required  robstoll/tutteli-spek-extensions#10 so that you can write a spec for `isSymbolicLInk` here, right? :grin:

**Comment by jGleitz** [comment]
> Let me guess, you required robstoll/tutteli-spek-extensions#10 so that you can write a spec for `isSymbolicLInk` here, right? :grin: 

Now that would be some next level trickery! :laughing: 

But actually, no, I wrote it mainly so I can add specs for the symbolic link handling behaviour of the file assertions.

**Comment by jGleitz** [comment]
I think an update is due: I am still actively working on this, but it proved to be a lot more involved than I expected.

I am trying to give the user helpful messages for all common file system cases. Unfortunately, there are quite a few of these cases. I want to make sure that the user can see the root problem, not just the failure (there a multiple reasons why something is not a file: it may not exist, not be accessible, its parent may not exist or be a file, ...)
I have all cases I could think of covered, except for symbolic link handling. I want to make sure that all symbolic links that were involved are being printed in case of a failure. I once debugged a problem on a colleague's machine where we did not realise that a symbolic link was involved in an upper level and was causing the issue. This functionality would have saved us a lot of time then.

I think it is particularly important to have great failure hints for IO related things because debugging them may be complicated or even impossible (files may have been deleted already or not be accessible, think CI).

**Comment by robstoll** [comment]
Take your time, no stress. In case you want that I already review something then you can always create a PR with the prefix `WIP` in the title (btw. WIP = Work In Progress).
And of course, there is always room for improvement. Once you are happy with your implementation we can already merge a first working version and you can still improve hints from there.
