### ISSUE TITLE
notToContain() should not fail if subject collection is empty

### ISSUE THREAD

**Issue by tenor-dev** [robstoll/atrium#1143]
### Affected Version

0.18.0

### API

fluent-en_GB

### Platform

jvm

### Kotlin Version

1.6.20

### How to reproduce the problem?

```kotlin
expect(emptyList<String>()).notToContain("Hello")
```

### Describe the bug

Currently it fails.

### Expected behaviour

Empty list never contains anything, so this should not fail.

**Comment by robstoll** [comment]
See kdoc of this function:
```
 * Expects that the subject of `this` expectation (an [Iterable]) has at least one element and
 * that it does not contain the [expected] value and neither one of the [otherExpected] values (if given).
 ```
Use `toBeEmpty()` if you expect that the list is empty.  That's a different test-case IMO.

But I guess you don't know whether the iterable is empty or not at the time you write your test. Correct?

**Comment by tenor-dev** [comment]
We would argue that it's unexpected that a lists of 1 random element would not fail the above test, but an empty one would.
In other similar frameworks (e.g. AssertJ) it works as expected, and most likely should here as well... No need for a separate function that will be hard to discover.

**Comment by robstoll** [comment]
@tenor-dev do you know by the time where you write the test whether the list is empty or not?

**Comment by angryziber** [comment]
@robstoll usually it is not known for sure, otherwise `toBeEmpty()` could be used.
But when somebody uses `notToContain()` - it means that they don't care what there is, it's just important that the given elements are missing, including if the subject is empty.

An example use case for that is a DB integration test, where you load list of items, check them, then delete an item, load the list again and check that the deleted item is not present.

**Comment by robstoll** [comment]
@angryziber Thanks for your feeback and sharing your use case. 

> I cannot imagine a use case

The reason why I included this check is outlined in detail in the discussion in #689. IMO it is basically smelly if you don't know whether your iterable has next elements or not. Many times, I would even claim most of the times, the outcome of an empty iterable (in tests) is very different than some value(s) are not among other values.
Taking your db example. I question your test setup if you don't know whether the table is empty after an operation or not. Are you sure you your implementation really does delete xy if the table is empty afterwards? Maybe you have implemented delete all by accident. Or you have accidentally consumed your one-time-readable iterable before your `expect` and the delete did not delete anything. It is exactly for such reasons that we included the check. It's not like it safes you from deleting more than you wanted (IMO you should still check that the iterable contains all but the one(s) you intended to delete) but it gives you a hint in case you run into the situation where your expectation failed because the iterable was empty.

> then it should be named notToBeEmptyAndNotContain(...) 

I basically agree, we already renamed `any`, `none` and `all` for this reason to `toHaveElementsAndAll`. We didn't rename `notToContain` by that time (even though `toHaveElementsAndNone` is basically the same). I'll reconsider if `notToContain` should be renamed but might well be that I'll just add the hint:
```
 ℹ️ use noToHaveElementsOrNone if you don't care about the empty case
 ```
 instead.

> which is probably the same as writing .notToBeEmpty().notToContain(...) - in case somebody needs exactly that.

Exactly, but with the difference that one cannot forget to write `notToBeEmpty` currently. IMO in tests it is way more important that a test fails because of a wrong usage (in other words one did not expect that `notToContain` also checks not empty) than a test which passes but only because a developer forgot to add `notToBeEmpty`.

**Comment by angryziber** [comment]
I remind you the basic philosophy of Unix utilities that proved over 40 years to be very successful - they should do one thing only and be composable.

That's why it doesn't make sense for `notToContain` to do an unexpected additional check of `notToBeEmpty`.
If somebody cares about that case, they should use it explicitly.

And please don't rename all method to be long and clumsy. We chose Kontlin and Atrium for conciseness.
Very long method names is a hint of them doing too many things at once, and generally is a code smell (of course, even worse if they are named shortly, but do some unexpected things)

**Comment by robstoll** [comment]
IMO you need to see the context where your utility is used. If we talk about business logic, then I am totally on your side, functions should do just one (small) thing and it is up to the developer to think carefully if a isNotEmpty check is required or not. However, if we talk about validation of code, then safety-first should be the credo. As already outlined, IMO it is better to have a false negative (failing test because test logic is wrong) than a false positive (passing test because test logic is wrong). Atrium is opinionated in this regard and I value avoiding potential bugs in test logic/avoiding wrong test data setup higher than the function should just do one thing.

> And please don't rename all methods to be long and clumsy. We chose Kotlin and Atrium for conciseness.

That's also the reason why I tend towards adding a hint to `notToContain` instead of renaming. 
One reason why I renamed `all` et al. to `toHaveElementsAndAll/...` was that one could add an own `all` which does not include the check. 

Talking about that, I could actually provide another jar `atrium-api-fluent-risky-en_GB` which contains those functions. This way I would satisfy both standpoints. Would that be a good compromise?

**Comment by angryziber** [comment]
It is not risky, but expected :-)
Probably too many atrium jars already.

Anyway, it seems you are not willing to fix that issue. Hopefully this was a conscious decision and not a bug, that you are defending, like it seems at a first glance.

We have spoken, you are to decide what to do about it.
Other libraries seem to do this right, but have other issues :-)

**Comment by robstoll** [comment]
@angryziber it's always good to get feedback. Thanks for that

> Hopefully this was a conscious decision and not a bug, that you are defending, like it seems at a first glance.

I guess, I wasn't as lucky as you have been in the past. I ran into bugs which were not covered by tests due to the missing `has at least one element` check in the test code. That's also the reason why I have baked this check into `notToContain`. Probably depends a lot on the expertise of your team and on how much time reviewers can spend to review code.

> Probably too many atrium jars already.

Would you use it though? Following the functions I would add to this jar:
- any
- none
- all

`notToContain("Hello")` can then be formulated with `none { toEqual("Hello") }`

And out of curiosity, what jars are you referring to? I guess you also depend on the bundle jar as show in [installation](https://github.com/robstoll/atrium#jvm)
What other atrium jars have you defined as dependency?

**Comment by angryziber** [comment]
@robstoll we currently use testImplementation("ch.tutteli.atrium:atrium-fluent-en_GB:0.18.0")
I haven't tried the infix version yet, which I may even prefer if it looks nice. Maybe should be a good pairing with mockk, which uses infix for `every {} returns`
