### ISSUE TITLE
Pass Iterable to  contains-like functions

### ISSUE THREAD

**Issue by jGleitz** [robstoll/atrium#119]
Any Platform.

## Code related feature
```kotlin
fun testWithExternalData(expectedContent: List<String>) {
    expect(tested).containsExactly(expectedContent)
}
```

the above is not possible, because `containsExactly` has only the overload that takes one element parameter and an additional varargs parameter. This is _very_ awkward to call with a given list (or am I missing something?):

```kotlin
fun testWithExternalData(expectedContent: List<String>) {
    expect(tested).containsExactly(expectedContent.first(), *expectedContent.drop(1).toTypedArray())
}
```

Note that something like the above is quite common to happen when writing data-driven or parameterized tests.

I am aware that adding an overload that takes an Iterable introduces ambiguity for iterables that contain iterables. Because of that, it might make sense to name the new functions differently:

```kotlin
fun testWithExternalData(expectedContent: List<String>) {
    expect(tested).containsExactlyThe(expectedContent)
}
```

Please be aware that this issue applies to all contains-like functions, also on other types like CharSequences.

**Comment by robstoll** [comment]
Thanks for the report. What would you expect if one passes an empty List, should the subject (`tested` in your example) then also be empty?

**Comment by jGleitz** [comment]
> What would you expect if one passes an empty List, should the subject (tested in your example) then also be empty?

Yes, I think it should, because we are using `containsExactly`.

>`containsExactlyElementsOf`

that seems like a much better name than my proposal!

**Comment by jGleitz** [comment]
Note: I would be glad to implement this as soon as we reach a consensus of whether and how you want to see this.

**Comment by robstoll** [comment]
Cool :sunglasses:, you might want to have already a look at https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution and I will look how we could add it to Atrium

**Comment by robstoll** [comment]
@jGleitz one thing I don't particularly like about it is that it clutters the API quite a bit for very little value and once introduced, we should probably add it to every function expecting `T, Array<out T>`
Would it be enough if you could have written:
```
fun testWithExternalData(expectedContent: List<String>) {
    expectedContent.toArguments { first, others ->
       expect(tested).containsExactly(first, *others)
    }
}
```
It's semantically not the same as `containsExactlyElementsOf` but its one single function which can be used in many places vs. many additional overloads.
I can still imagine to add containsExactlyElementsOf in a later step if it is really still needed. I also think that we would no longer have to add an `...ElementsOf` to every function expecting `T, Array<out T>` with `toArguments` in place

**Comment by jGleitz** [comment]
Of course, the solution you suggest would work _technically_.

But I would argue that it is not a very good solution, because it makes the test significantly less easy to read.
I think that it is important that test logic is easily readable for all programmers, even those that are not very familiar with the libraries used.

In this case, if I did not know about this specific problem, it would not be obvious at all for me what the `toArguments` call is doing and why we need it.

**Comment by robstoll** [comment]
Good point but I still have a bad feeling adding it. There is another issue, it seems hard to get a consistent behaviour. 
```
// grey zone, could be looked as alternative to isEmpty, but isEmpty would have been better
expect(listOf(1,2)).containsExactlyElementsOf(listOf()) 

expect(listOf(1,2)).containsElementsOf(listOf()) // programmer error IMO
expect("hello").containsElementsOf(listOf()) // programmer error IMO
```
Also, this feature is most likely only used in case of data-driven testing and thus should not be too present in the API. How about we adding it to `contains.inOrder.only.elementsOf` and to `contains.inAnyOrder.only.elementsOf` but check that the given list is not empty?

**Comment by jGleitz** [comment]
> Also, this feature is most likely only used in case of data-driven testing and thus should not be too present in the API.

I have the impression that we have different styles of writing tests. For me, it is fairly common to write a unit test and then feed it with a set of different test data. JUnit 5’s [`@ParameterizedTest`](https://www.baeldung.com/parameterized-tests-junit-5) is great for it, but you can do it in almost all frameworks. It helps to not repeat oneself and still make sure that different cases are covered without much effort.

So I often have my test data in a variable instead of spelling it out directly in the code. For me, it would be important to have it in the API because I would use it often.

> There is another issue, it seems hard to get a consistent behaviour.

I think it is true that the examples you mention would be problematic if found in some code base. But I do not think that they are an issue. Because in all three examples, the semantics are obvious. You can read the lines out loud and instantly make sense of them.

At the end of the day, it is not a library’s job to keep programmers from writing illogical code. It is only its job to keep them from writing illogical code _accidentally_. So a library should not contain any surprise or unexpected behaviour. But neither is the case for any of the examples. That is why I think it is fine.

**Comment by robstoll** [comment]
No worries, I write data-driven tests myself. I see your point about readability but there is more than that. New functionality also has to pay off. Adding it to `contains.inOrder.only.elementsOf` seems fine with me, as it does not pollute the Expect API. But only the very specific `contains` API.

> I think it is true that the examples you mention would be problematic if found in some code base. But I do not think that they are an issue

Not if we check that the passed list is not empty => if kotlin had a NonEmptyList then I would use it here so that one does not have to wait until runtime checks apply. Without a check on the other hand, I think it is problematic and the semantic is not obvious for me at all.

> At the end of the day, it is not a library’s job to keep programmers from writing illogical code. It is only its job to keep them from writing illogical code accidentally.

I think a good library should also prevent users from writing illogical code, at least at runtime. I could have made `containsExactly` expecting only a vararg but introduced the first parameter on purpose. 

But back to the issue as such. We can chat about readabilty if you like (you find me on [slack](http://slack.kotlinlang.org/)) Let me explain my reasons why I think it does not pay off in more detail.
- not adding does not hinder data-driven tests to be written
- adding it means more maintenance
- adding it means also we have more contains methods in the API. Currently we have:
![image](https://user-images.githubusercontent.com/5557885/63459048-30691200-c454-11e9-9de6-f1e3af8cd732.png)
  quite small and clearly, we could already have added things like `containsInAnyOrderOnly`, `containsNotOrAtLeast` etc. IMO a good API is similar to a good UI, too many functionality confuse the user in the end and it is better to have the most important functions at hand and be able to find the others easily.
- we can still add `containsExactlyElementsOf` in a later version if it is a feature which is used very often by many people.

**Comment by jGleitz** [comment]
I think when `contains.*.elements` will be added (please not only for iterables but for other search-like behaviours, like on strings, too!), the main request of this ticket is served.

Regarding how the API looks like, I understand your point of view and accept it, even though I disagree. It seems to boil down to how we weight the different, valid goals there are.

**Comment by robstoll** [comment]
I am closing this issue, I have created separate issues for each feature and also #131 which needs votes in order that I implement it. Feel free to vote as well and maybe you can convince other peers to vote as well.
