### ISSUE TITLE
samples for Iterable.toContain.atLeast.butAtMost

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1546]
## Code related feature

Following the things you need to do:

*api-infix*
- [ ] add a `butAtMost` method in IterableLikeToContainCheckerSamples (see CharSequenceToContainCheckerSamples
- [ ] link in the KDoc of the corresponding function in iterableLikeToContainCheckers.kt to the sample via `@sample` (see charsequenceToContainCheckers.kt)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by fergbaldo** [comment]
I'll work on this

**Comment by fergbaldo** [comment]
Hi @robstoll ,
I have completed a solution for this issue in the same manner that I completed Issue #1545  , which I solved in Pull Request #1585 , and in the same manner as #1548 , which I solved in Pull Request #1586 

Please review this and let me know if any changes need to be made. If no changes are required, then I can likely complete another couple of similar issues today.

I would like to note that the build for this project would produce consistent errors on my devices due to 'missing' temporary files, before and after my edits. As such, I produced this code after a study of other functional relevant code in the project.
