### ISSUE TITLE
Build Script references java 7 and java 9

### ISSUE THREAD

**Issue by dgoetsch** [robstoll/atrium#18]
I saw a comment by you in stack overflow, not enough reputation to comment..

I noticed your build script references java 7 and java 9. If it isn't a bug, could you write a comment explaining why?

**Comment by robstoll** [comment]
My target is java 7 but I include a proper module-info.java so that users using jdk9 can already get it right --- rather than providing an automatic-module now and jdk9 users might have to fix things when I switch to jdk9 entirely. So, when I release my project I compile the module-info.java to *.class with jdk9 and then compile kotlin code with the kotlin compiler to jdk7 (might be that it is even jdk6 compatible).
I close this issue but feel free to ask other questions.
