### ISSUE TITLE
Simplify PathAssertionsSpec, remove SymlinkTestBuilder

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#251]
*Platform* (jvm, js, android): jvm
*Extension* (none, kotlin 1.3, jdk8): jdk8

## Code related feature
The setup with the SymlinkTestBuilder + MaybeLink is a bit over-engineered IMO and is hard to comprehend for newcomers. A spec should be written in a simpler manner without inheritance involved. I suggest we rewrite it to a function based solution.

**Comment by jGleitz** [comment]
I wrote this piece of code and agree that it is more complex than your typical unit test should be.

Please be aware that by removing the `withAndWithoutSymlink` function, you either double the amount of written unit test code lines or reduce the tested cases.

When I wrote this logic, I was aware that it was pretty heavyweight for unit tests and that it added complexity. I felt like it was worth it because it saves a lot of duplicated logic. I also thought that the `withAndWithoutSymlink` function and the `MaybeLink` data type are sufficiently expressive. I hoped that while it would be difficult to understand _how_ they work, it would be sufficiently easy to understand _what_ they do.

If anybody finds a simpler way to achieve this: By all means do! I don’t like the complexity, either. _However_, I want to warn against simply duplicating the logic, I feel like this would be the worse solution.

**Comment by robstoll** [comment]
closing for now, newcomers seem to have coped with it quite well
