### ISSUE TITLE
nullable Long! cannot be expected not to be null

### ISSUE THREAD

**Issue by Centaur** [robstoll/atrium#90]
*Affected Version*: 0.8.0
*API* (cc or cc-infix): expect().notToBe()
*Platform* (JVM, JS, Android): JVM

## How to reproduce the problem  
I am calling some java code with this definition
```java
class A {
  public Long v
}
```
from kotlin code
```kotlin
// retrieve a:A from java
expect(a.v).notToBe(null)
```

## Describe the bug
`A::v` has type `Long!` and is definitely nullable, but the compiler matches this code with 

```kotlin
fun <T : Any> expect(subject: T)
```
and complains `Null can not be a value of non-nullable TypeVariable(T)` 

## Expected behaviour
the above kotlin code should compile

**Comment by robstoll** [comment]
Thanks for the bug report, unfortunately I cannot modify the behaviour of Kotlin how it treats platform types (e.g. `Long!`). The problem is that kotlin decides that it treats `Long!` as `Long` and that is why it uses the overload with `T: Any`. See the section [Java Interoperability](https://github.com/robstoll/atrium#java-interoperability) in the readme.

Atrium provides a workaround, you can write the above as:
```
import ch.tutteli.atrium.domain.builders.utils.nullable

expect(nullable(a.v)).notToBeNull{}
```

**Comment by robstoll** [comment]
@Centaur Atrium has currently not a `notToBe(null)` function as I assume that you always want to assert more than just `it is not null` e.g. `expect(nullable(a.v)).notToBeNull{ isLessThan(2L) }`
Would you appreciate if Atrium had `notToBe(null)` in addition?
